### PR TITLE
Fixes validation of AWS::URLSuffix

### LINKED ISSUE #173: Failure to validate templates that use the AWS::URLSuffix psedo parameter
When validating templates that include the `AWS::URLSuffix` pseudo parameter, the value is not recognised and an error is thrown.

Steps to reproduce:
1. Execute `cfn-lint validate sample.json`, where `sample.json` contains the following:
```json
{
    "Resources": {
        "TestLambdaPermissionEventsRuleSchedule1": {
            "Type": "AWS::Lambda::Permission",
            "Properties": {
                "FunctionName": "test",
                "Action": "lambda:InvokeFunction",
                "Principal": {
                    "Fn::Join": [
                        "",
                        [
                            "events.",
                            {
                                "Ref": "AWS::URLSuffix"
                            }
                        ]
                    ]
                },
                "SourceArn": "arn:aws:lambda:us-east-1:123456789012:function:Test"
            }
        }
    }
}
```

Expected outcome: no validation errors
Actual outcome:
```
0 infos
0 warn
1 crit
Resource: Resources > TestLambdaPermissionEventsRuleSchedule1 > Properties > Principal
Message: Referenced value AWS::URLSuffix does not exist
Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html

Template invalid!
```

I'm working on a PR for this. It's a simple fix, I just need some tests

### PR DESCRIPTION
**Pull request by nskoufis**
Fixes #173 

This adds the AWS::URLSuffix to the reference value overrides reference
data, as well as to the type used for this value in code.

This is a perfectly valid pseudo parameter (as per
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-urlsuffix)
but was causing an error at
https://github.com/nskoufis/cfn-lint/blob/master/src/validator.ts#L680

### CODE REVIEW

**Comment by martysweet** [comment]
Great thanks, can you cleanup the PR? Looks like lib/ was committed

**Comment by nskoufis** [comment]
Done, sorry about that, anything else you'd like me to do?

**Comment by martysweet** [comment]
Thanks @nskoufis, can you also drop the `package-lock.json`, haven't got round to agreeing anything on that (and would belong in a separate PR)

**Comment by martysweet** [comment]
Great stuff, thanks :tada:

**Pull request merged**
