### PR TITLE
Update CHANGELOG for v1.9.0 

### PR DESCRIPTION
**Pull request by martysweet**

### CODE REVIEW

**Comment by martysweet** [comment]
Hi @RazzM13, just updated the sam spec from the Github repo link and run the transformation code and the majority of the SAM-20161031 test suite is failing. Any ideas?

**Comment by RazzM13** [comment]
Hi @martysweet, unfortunately, I believe they just introduced the `allOf` keyword into the schema and I didn't account for this case, we'll have to look into it and introduce support for it... I can certainly have a look at it, sometime next week. Sorry for the inconvenience.

**Comment by martysweet** [comment]
No worries, we shall hold off until then. Let me know if there is anything you need.

**Comment by RazzM13** [comment]
Hi @martysweet, just managed to get to this, will keep you updated :)

**Comment by RazzM13** [comment]
Hey @martysweet, basically *SAM* introduced additional variability within their *JSON Schema*, in regards to the resource / property type definition's `properties` section. Now, I've changed the `sam2CFNUtils` to account for this by recursively walking each of the `allOf`, `anyOf` and `oneOf` operator items and combining the results within a single map however, this does not account for the`required` properties as I'm not really sure how to assemble these in a sane manner...

FWIW, IMO, I believe that for the time being we should just leave this as is because, due to the nature of *JSON Schema* operators, future breakage is to be expected here and perhaps it's best to tackle this when the situation demands it (i.e. new schema style from *SAM* :)) or complaints arrive.

Let me know you're thoughts and especially if you're now able to update the schema.

**Comment by martysweet** [comment]
Thanks @RazzM13, will have a play and hopefully push a release on Monday

**Pull request merged**
