### PR TITLE
WIP - Obscure value mocking

### LINKED ISSUE #160: Obscure value mocking
The current way of mocking values that are required throughout the validation process does not provide users with any sort of information that mocking is taking place or what values are being guessed and used in the validation process thus, potentially inducing novice users to the fallacy that the validation for the affected items is not up to par, unless otherwise hinted via the README or the command-line usage prompt.

Furthermore, there are incosistencies in the way mock values are being generated / used and no way of detecting conflicting values that refer to the same entity; with the introduction of 4ae1383 one such irregularity has arrisen for resource attributes, which previously had their values generated during `assignResourcesOutputs`, are now being overriden during a call to `fnGetAtt` to satisfy list-type properties / intrinsic requirements.

Even though I am an advocate for ItJustWorks (TM), imperfections such as these can have a negative impact on a project's user experience and codebase maintenance in the long term therefore, to alleviate the aforementioned, I would like to suggest that the following be implemented:
- [ ] A register of mocked attribute values that exhibits a dual role of notifying a user about the mocked values that are in play as well as keeping track of potential value conflicts for the same attribute that may arrise during runtime and, notifying if such a conflict occurs;
- [ ] A centralised way of generating mocked values based on value type and/or attribute type;
- [ ] Contextual resolution for mocked values that should be based on the need of a specific value during validation in the template's current position as well as within an intrinsic expression or a chain of intrinsic expressions.

### PR DESCRIPTION
**Pull request by RazzM13**
Fixes #160

### CODE REVIEW

**Comment by martysweet** [comment]
@RazzM13 is this still WIP?

**Comment by martysweet** [comment]
Ok, lets put this along with the other changes into the v1.8.0 release. #167 and #156 are going to clash horribly so we need to work out the best order to merge them in.

**Comment by RazzM13** [comment]
I was actually wondering about that too, though I haven't really had a chance to look at the changes imposed by #156 ...

**Comment by RazzM13** [comment]
Hey @martysweet, now that *SAM support* is in `master`, should I now have a look at this?

**Comment by martysweet** [comment]
Sounds like a plan @RazzM13. We have #198 which this type of functionality could have been helpful in.

**Comment by RazzM13** [comment]
Hey @martysweet, apart from the merge conflict is there anything else that is blocking this? :)

**Pull request closed without merging**
